$f = 'C:\Users\ihsan\Desktop\BOOK\web\src\lib\marketing-data.ts'
$enc = [System.Text.Encoding]::UTF8
$c = [System.IO.File]::ReadAllText($f, $enc)
$lines = $c -split "`n"

# Section 1 (line 426, index 425)
$lines[425] = '      ["What is EPUB and how does it work?", "EPUB is an open standard developed for electronic publishing, and its name comes from the words ''electronic publication.'' Its most fundamental feature is its reflowable structure: text automatically reshapes itself according to the reader''s screen size, resolution, and font preferences. When reading on a phone, lines narrow and adapt; on a tablet, they widen; on an e-reader, the user can increase or decrease font size — the content remains readable under all conditions. This flexibility has made EPUB the standard for digital distribution. Amazon Kindle, Apple Books, Kobo, Google Play Books, and nearly all major e-book platforms support the EPUB 3 format. Amazon used to recommend the .mobi format; however, since 2022, it has adopted EPUB as its primary format. In short, if you plan to distribute digitally, upload to KDP, or send directly to the reader, EPUB should be your primary output."],'

# Section 2 (line 427, index 426)
$lines[426] = '      ["What is PDF, and when should you use it?", "PDF stands for ''Portable Document Format'' and was developed by Adobe in the early 1990s. Its core characteristic is fixed layout: pages appear exactly as designed — font size, line spacing, image placement, and page margins never change. No matter which device or software opens it, the appearance stays the same. This makes it ideal for print: files sent to a printing house, physical book production, full-page designed guides, or certificates all require PDF. If you want to publish a paperback or hardcover book on Amazon KDP, the interior text and cover must be prepared as separate PDF files. On the other hand, PDF is cumbersome for digital reading in many ways: reading on a phone screen is tiring, you constantly need to zoom in and out to fit lines, and the font size cannot be adjusted by the user. This is why EPUB is preferred over PDF for uploading to e-book platforms."],'

# Section 3 (line 428, index 427)
$lines[427] = '      ["Which format does KDP require?", "Amazon KDP expects two different formats for two different publication types. To publish a digital book (Kindle eBook), the EPUB 3 format is required, and KDP accepts this format directly. Before 2022, the .mobi format was also widely used, but Amazon now officially recommends EPUB, and it is preferred for new uploads. KDP''s own preview tool, Kindle Previewer, lets you upload your EPUB file and simulate how it will look on a Kindle screen — running this check before uploading is a good habit. To publish a printed book (paperback or hardcover), PDF is required. The interior text is prepared as a single PDF, and the cover as a separate PDF. The cover PDF''s dimensions are determined by the page count because the spine thickness changes with the number of pages. KDP offers a free cover template tool to simplify this calculation. In summary: EPUB for digital, PDF for print — if you''re planning to do both, you need to have both formats ready."],'

# Section 4 (line 429, index 428)
$lines[428] = '      ["Which format should you get first?", "The practical recommendation is clear: get EPUB first, and leave PDF for later. Once you have the EPUB, you can easily check the book''s structure, chapter ordering, heading hierarchy, and overall flow in an e-reader, Kindle Previewer, or browser-based tools. Which chapter heading appears at the wrong hierarchy level, does the table of contents show the correct links, does the flow make sense — it is much easier to see these in EPUB. Catching and fixing structural issues here saves time and prevents unnecessary revision cycles in PDF. If you are only doing digital distribution, you may not need PDF at all. If you are considering print, follow this order: first verify content and structure with EPUB, then check the print layout with PDF. Getting both at the same time is also possible; however, from a quality-control perspective, EPUB should always be the first step."],'

# Section 5 (line 430, index 429)
$lines[429] = '      ["What to watch out for during the conversion process", "When producing EPUB, the most critical point is the heading hierarchy. If H1 for the book title, H2 for chapter headings, and H3 for sub-chapter headings are not marked correctly, the table of contents will be generated incorrectly, and navigation will break in some reader apps. Check whether images are embedded inside the EPUB — linked images may not appear on some platforms. Additionally, testing your EPUB file with a validation tool like epubcheck before publishing will prevent potential KDP rejection notices. When producing PDF, margins, font embedding, and page size are of critical importance. KDP offers standard trim size options for printed books; the most common is 6x9 inches. Images with bleed areas require additional settings. Book Generator handles most of these technical details on your behalf and produces platform-compatible outputs; still, skipping the final check step is not a good habit."],'

# Section 6 (line 431, index 430)
$lines[430] = '      ["Summary: choose the format based on your purpose", "EPUB: digital reading, e-book platforms, Amazon Kindle, Apple Books, Kobo, mobile devices. The user can adjust font size, text adapts to screen size, and file size is small. PDF: print, fixed layout, printer file, KDP paperback interior and cover. Design is preserved pixel-perfectly and appears platform-independent. Both formats may be necessary for different purposes, and neither can replace the other. Always start with EPUB: verify the structure there, check the content, and then move to PDF once approved. Book Generator offers both formats as export options; getting both at the same time requires no extra effort."],'

$c = $lines -join "`n"
[System.IO.File]::WriteAllText($f, $c, $enc)
Write-Host "All 6 sections replaced OK"
